// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataEfCore.EntityModels
{
    public partial class Stucourseschedule
    {
        public Guid Id { get; set; }
        public Guid Studentid { get; set; }
        public Guid Cscheduleid { get; set; }
    }
}