// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataEfCore.EntityModels
{
    public partial class Sysadmin
    {
        public Guid Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public DateTime? Initdate { get; set; }
        public DateTime? Modifydate { get; set; }
    }
}